-- Create Database
CREATE DATABASE IF NOT EXISTS medical_inventory;
USE medical_inventory;

-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'nurse', 'worker') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert Sample Data
-- Passwords are 'password123' hashed with BCRYPT (Cost 10)
-- You can generate new hashes using PHP's password_hash('your_password', PASSWORD_DEFAULT)

INSERT INTO users (username, password, role) VALUES 
('admin', '$2y$10$4EH2p9qs/fu4v2WBbLl5/eM/vjmeaqzHu5IKk63FW1xfBfUjonfMy', 'admin'),
('nurse', '$2y$10$4EH2p9qs/fu4v2WBbLl5/eM/vjmeaqzHu5IKk63FW1xfBfUjonfMy', 'nurse'),
('worker', '$2y$10$4EH2p9qs/fu4v2WBbLl5/eM/vjmeaqzHu5IKk63FW1xfBfUjonfMy', 'worker');

-- NOTE: Replace the password hashes above with real hashes generated by your application or a tool.
-- Example PHP to generate hash: echo password_hash('password123', PASSWORD_DEFAULT);
